### PR TITLE
Fixing dead link

### PR DESCRIPTION
**Pull request by AdrianMachado**
I am guessing this is the new destination for where the old link would've taken you.

### CODE REVIEW

**Comment by AdrianMachado** [comment]
@landsman @ricosmall  can you take a look at this please?

**Comment by AdrianMachado** [comment]
@jackesdavid  @johnatandias

**Comment by landsman** [comment]
please merge it :)

**Comment by AdrianMachado** [comment]
@landsman unfortunately it won't let me without write access
image

**Comment by AdrianMachado** [comment]
@landsman @ricosmall @jackesdavid @johnatandias ping, pls merge this in

**Comment by ricosmall** [comment]
@AdrianMachado sorry, I have no access to merge your pr.

**Comment by tushar-prox** [comment]
After recent changes, this link update will not work.

I have updated the doc and generated #25 with all link changes.

**Pull request closed without merging**
